### ISSUE TITLE
No Dialog shown

### ISSUE THREAD

**Issue by rkorn86** [amonakov/libgl-switcheroo#4]
I've just followed the README, but I dont get any dialog asking me for my choice.
Did I miss something?
I even dont understand your export Line.
Why does LD_LIBRARY_PATH contains a the $LIB variable? Where does this variable come from?
`setti@Lappy - 12:24:09 - ~ $ echo $LD_LIBRARY_PATH 
/tmp/libgl-switcheroo-setti/fs/$LIB`
If i strace glxinfo i get a lot of "file not found" messages like this:
`stat("/tmp/libgl-switcheroo-setti/fs/lib", 0x7fffdae34360) = -1 ENOENT (No such file or directory)`

Indeed this directory does not exist.

``` bash
setti@Lappy - 12:23:19 - ~ $ ls /tmp/libgl-switcheroo-setti/
insgesamt 0
drwxr-xr-x  3 setti setti  80  2. Jul 12:09 .
drwxrwxrwt 18 root  root  400  2. Jul 12:23 ..
drwxr-xr-x  2 setti setti  40  2. Jul 12:15 fs
srwxr-xr-x  1 setti setti   0  2. Jul 12:09 socket
```

``` bash
setti@Lappy - 12:23:22 - ~ $ ls /tmp/libgl-switcheroo-setti/fs/
insgesamt 0
drwxr-xr-x 2 setti setti 40  2. Jul 12:15 .
drwxr-xr-x 3 setti setti 80  2. Jul 12:09 ..
```

**Comment by amonakov** [comment]
`$LIB` in LD_LIBRARY_PATH is a special token that is expanded by the dynamic linker, not the shell; that is why the dollar sign is escaped.

It looks like your issue is that libgl-switcheroo is not running. You can run it with `-d` flag in a terminal to get FUSE debug output.

**Comment by rkorn86** [comment]
``` bash
setti@Lappy - 08:36:37 - ~ $ LC_ALL=C libgl-switcheroo /tmp/libgl-switcheroo-setti/fs -d
gtkglswitch: fatal: GTK initialization failed: Unknown option -d
setti@Lappy - 08:36:59 - ~ $ LC_ALL=C libgl-switcheroo -d /tmp/libgl-switcheroo-setti/fs
gtkglswitch: fatal: GTK initialization failed: Unknown option -d
```

same for gtkglswitch

**Comment by rkorn86** [comment]
sorry, seems my distribution used an old git commit.... -d works. im debugging now.

**Comment by rkorn86** [comment]
got everything working.... dont know the real cause... sorry!

**Comment by amonakov** [comment]
If you're on Arch that's probably because the [pkgbuild in aur](https://aur.archlinux.org/packages/libgl-switcheroo-git/) contains a typo.

**Comment by rkorn86** [comment]
that was the cause :)
