### ISSUE TITLE
Steam?

### ISSUE THREAD

**Issue by thisischrys** [amonakov/libgl-switcheroo#7]
Tried this a few years ago on my old laptop, seems like still the same issue?
Will this ever be fixed?
Any workarounds or dirty hacks I could try?
(I just edited my launcher to use primus, but as I also use my GPU in KVM sometimes (which makes it unavailable to X) it would be handy to get the popup)

**Comment by amonakov** [comment]
It's unclear what issue you're talking about.

**Comment by thisischrys** [comment]
The popup doesn't show for steam.

**Comment by thisischrys** [comment]
dead
